# -*- coding: utf-8 -*-
"""HotelBookingCancellationModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149ePdPTuxPaeHfCck8fcv-h8x-oGiL7A
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

df =pd.read_csv('/content/booking.csv')

df

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

LE = LabelEncoder()

df.head()

df['Booking_ID'] = LE.fit_transform(df['Booking_ID'])
df['type of meal'] = LE.fit_transform(df['type of meal'])
df['room type'] = LE.fit_transform(df['room type'])
df['market segment type'] = LE.fit_transform(df['market segment type'])
df['booking status'] = LE.fit_transform(df['booking status'])
df['date of reservation'] = LE.fit_transform(df['date of reservation'])

df

X = df.drop(columns = 'booking status',axis=0.1)
Y = df['booking status']

print(X)

"""#1 = not cancelled
#0 = cancelled

"""

print(Y)

df['booking status'].value_counts()

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,stratify=Y,test_size=0.2,random_state=42)

model = LogisticRegression()

model.fit(X_train,Y_train)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

print("Accuracy Score IS:",test_data_accuracy)

df

input_data = (36281,	2,	0,	1,	3,	0,	0,	0,	34,	4,	0,	0,	0,	107.55,	1,	43	)

numpy = np.array(input_data)

numpy.reshape(1,-1)

reshape = numpy.reshape(1,-1)

reshape

prediction = model.predict(reshape)
if prediction == 1:
  print("NO CANCELLATION !!!")
else:
  print("CANCELLATION ACCQUIRED !!!")

